### ISSUE TITLE
UI goes away after enter configure settings

### ISSUE THREAD

**Issue by gmook9** [guygreenleaf/ChatGPT-Lite#1]
After entering the fields on the **Configure** section the UI breaks
![borken_full](https://i.ibb.co/jWqxSRN/bbc1.png)

Fixed after a **ctrl + r**
![broken](https://i.ibb.co/gP7k2qX/bbc2.png)

**Comment by guygreenleaf** [comment]
Having trouble reproducing this - but working on an overhaul of the storage system to use VS Code's native storage system instead of using localstorage (which admittedly is probably the issue and not ideal or "best practice" in this scenario).

**Comment by gmook9** [comment]
> 

Thank you for looking into this issue and providing an update on the progress. I appreciate your efforts to improve the storage system in the VS Code extension and addressing the potential bug caused by the use of local storage.

**Comment by guygreenleaf** [comment]
don't patronize me bud!

**Comment by gmook9** [comment]
> 

it was ChatGPT!

**Comment by guygreenleaf** [comment]
This should be fixed with 863b286
